name: my-first-workflow
on: push

jobs:
  job1:
    name: JOB1
    runs-on: ubuntu-latest
    steps: 
      - name: running a command on job1
        run: echo "My first workflow"
      - name: checking date
        run: |
          date
          ip a
          whoami
          cat /etc/os-release
